jolibrain/joliGEN

models/cut_semantic_mask_model.py
We have to compute g backward first because it uses pfb which is a semantic prediction made by the network f_s during forward and the weights of f_s have to remain the same.
=> fix: in place gradient error with f_s

models/cycle_gan_model.py, models/modules/mobile_modules.py, models/modules/resnet_architecture/mobile_resnet_generator.py, models/modules/resnet_architecture/resnet_generator.py, models/networks.py, options/base_options.py, scripts/export_onnx_model.py
This adds padding control, by setting `--G_padding_type` to `zeros`, it allows generator models to be exported to tensorRT. This is because tensorRT does not support non-constant padding nor padding with other values than 0...
=> chore: added control over padding params, for export of generators to tensorRT

util/util.py
I add clamping between -1 and 1 in tensor2im function. It fixes the use of sty2 generator because sty2 can produce output outside this range (unlike other generators such as resnet for example) and this is not a desired behavior.
=> fix: add clamping in tensor2im function

train.py
We used to have leaked semaphores when stopping the training since we started using DDP. Now it's fixed with a signal handler and `torch.distributed.destroy_process_group` method.
=> fix: use signal handler to kill all the processes

models/cut_semantic_mask_model.py
Displaying of out_mask loss didn't use to work when multigpu.
=> fix: computation of out_mask loss when multigpu

data/image_folder.py, data/online_creation.py, data/unaligned_labeled_mask_online_dataset.py, options/base_options.py, train.py
When using `_semantic_mask` models, we used to preprocess images in order to crop images around their bounding boxes. Now it's done online during data loading with the new dataset mode `unaligned_labeled_mask_online`. 
It differs from `unaligned_labeled_mask` in only one way. Indeed, instead of having `path_to_image.jpg path_to_mask.jpeg` in `paths.txt` file, we now have `path_to_image.jpg path_to_bbox.txt`.
=> feat: online dataset creation

data/unaligned_labeled_mask_dataset.py
This is a tentative fix for `unaligned_labeled_mask` datasets that fail on missing `index_B` variable.
=> fix: unset index_B for unaligned mask offline datasets

data/base_dataset.py
This fixes simple runs such as:
```
python3 train.py --dataroot /path/to/data/horse2zebra/ --model cut 
```
=> fix: validation with no label, e.g. simple cut model

models/modules/cut_networks.py
`netF` used to be initialized on first gpu and then transfer to another one. Due to pytorch/pytorch#70048, `netF` had wrong weights on the new gpu.
=> fix: netF is initialized on the right gpu

models/base_model.py, models/cut_model.py, models/cycle_gan_model.py, models/re_cut_semantic_mask_model.py, models/re_cycle_gan_semantic_mask_model.py, options/base_options.py, train.py, util/network_group.py
This PR adds EMA over G, in the manner of https://arxiv.org/pdf/1710.10196.pdf and http://www.cvlibs.net/publications/Sauer2021NEURIPS_supplementary.pdf
New options:
- `--G_ema` boolean
- `--ema_decay` which defaults 0.999
Notes:
- EMA could apply to D, it seems it is done in https://arxiv.org/pdf/1710.10196.pdf 
- I've seen two 'views' of EMA: one in which G_ema is kept on the side to generate samples, one where G is updated as well. We follow the second one since it prevents from re-generating the fake samples, metrics, etc...
- The reference theoretical paper on EMA for DL is https://openreview.net/pdf?id=SJgw_sRqFQ from ICLR 2019
=> feat(ml): exponential moving average for G

models/base_model.py, models/cut_model.py, models/cycle_gan_model.py
Quick fix for a bug introduced by https://github.com/jolibrain/joliGAN/pull/111. `APA_img` was added to `visual_names` even when `APA` option was false.
=> fix: APA_img is only added to visual names APA option is true

models/base_model.py, models/configs/segformer/segformer_config_b0.py, models/configs/segformer/segformer_config_b1.py, models/configs/segformer/segformer_config_b2.py, models/configs/segformer/segformer_config_b3.py, models/configs/segformer/segformer_config_b4.py, models/configs/segformer/segformer_config_b5.py, models/cut_model.py, models/cycle_gan_model.py, models/cycle_gan_semantic_mask_model.py, models/modules/resnet_architecture/mobile_resnet_generator.py, models/modules/resnet_architecture/resnet_generator.py, models/modules/segformer/segformer_generator.py, models/modules/segformer/utils.py, models/networks.py, options/train_options.py, train.py
We can now use segformer (from https://github.com/open-mmlab/mmsegmentation) to compute attention masks.
New librairies needed :
- `mmcv-full`
New options : 
- `config_segformer path_to_segformer_config_file` : path_to_segformer_config_file needs to point a segformer configuration file (basic config file is `./configs/segformer/segformer_config_b3.py `)
Example of commandline : 
```
python3 train.py --dataroot path_to_dataset--checkpoints_dir path_to_checkpoint_dir--name test_segformer --model cut --netG segformer_attn --display_env test_segformer --dataset_mode unaligned --config_segformer ./configs/segformer/segformer_config_b3.py
```
=> feat: segformer can be used for attention masks generation

models/base_model.py
Fix f_s backward when using more than one gpu. It produced an inplace modification which leaded to an backprop error.
Source : https://discuss.pytorch.org/t/custom-methods-in-distributeddataparallel/77114/4
=> fix: f_s backward when multigpu

util/util.py
Images were clamped between -1 and 1, so it wasn't possible to display masks with more than one class.
=> fix: mask display when more than one class

models/modules/projected_d/discriminator.py, models/modules/projected_d/projector.py, models/networks.py, options/base_options.py
We can now choose between a pretrained efficient net or a pretrained Mixvisiontransformer as feature extractor for projected D.
New options :
- `--D_proj_network_type` to choose between efficientnet and transformer feature_extractor
- `--D_proj_config_segformer`path to segformer config file
- `--D_proj_weight_segformer` path to segformer weights
Usage : 
```
python3 train.py --D_proj_config_segformer path/to/segformer_config.py --D_proj_weight_segformer path/to/segformer_weight.pth --D_netD projected_d `--D_proj_network_type` transformer
```
=> feat: pretrained segformer backbone (mit) as feature extractor for projected D

data/unaligned_labeled_mask_dataset.py
Options names weren't updated in a former PR for unaligned labeled mask dataloader
=> fix: new options names for unaligned_labeled_mask

models/cut_semantic_mask_model.py, options/train_options.py
With removing object task, we train `f_s` to detect an object on domain A images. So, it should predict only zeros (ie no object detected) on fake B images.
Usage :
```
python3 train.py --train_mask_for_removal
```
=> feat: use label 0 in domain B for object removal

models/modules/utils.py, models/networks.py, options/base_options.py
Add option to choose between f_s models (instead of light/not light)
Deleted option:
- `train_f_s_light`
New options : 
- `f_s_net` : choose f_s network between vgg (old not light), unet (old light) and segformer (new)
- `f_s_config_segformer`: path to segformer config
- `f_s_weight_segformer` : path to segformer weights (torch or torchscript)
Usage:
```
python3 train.py --f_s_net segformer --f_s_pretrained --f_s_config_segformer path/to/config
--f_s_weight_segformer path/to/weights
```
=> Feat load pretrained f s

models/modules/projected_d/blocks.py, models/modules/projected_d/discriminator.py, models/modules/projected_d/projector.py, options/base_options.py
Use timm models as feature extractor for projected D.
New choices for `D_proj_network_type`:
- `vitbase` : vit_base_patch16_224
- `vitsmall`: vit_small_patch16_224
- `vitsmall2`: vit_small_r26_s32_224
```
python3 train.py  --D_netD projected_d --D_proj_network_type vitsmall --train_gan_mode projected
```
=> Timm model projected feature extractor

options/base_options.py, tests/test_run_semantic_mask.py
Fix a typo in `f_s_semantic_nclasses` and add a comment to remember why we do not raise an error when there is a wrong option name in  a json option file.
=> fix: wrong option name in test and add comment in json option loading

models/cycle_gan_semantic_mask_model.py, tests/test_run_semantic_mask.py
Unit tests in `tests/test_run_semantic_mask.py` fail with cyclegan, something related to f_s:
```
create web directory /data1/beniz/checkpoints/tests/joligan_utest_cycle_gan_semantic_mask/web...
../aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [0,0,0], thread: [960,0,0] Assertion `t >= 0 && t < n_classes` faile
d.
```
The exact same mini dataset works fine with CUT.
I've initiated this PR with small fixes to cyclegan with semantic masks that I did find when looking for a fix to the issue.
=> fix: cyclegan semantic mask failure with f_s

options/base_options.py
There should be no train dependency in `BaseOptions`, this PR just makes sure we have a workaround.
=> fix: circumvent isTrain in base options

.github/workflows/github-actions-doc-options-update.yml, .github/workflows/requirements_github_actions.txt
Install all requirements to prevent github action doc generation from failing.
=> fix: install all requirements for github actions

models/modules/projected_d/projector.py, models/modules/resnet_architecture/resnet_generator.py
Fix bug introduced by https://github.com/jolibrain/joliGAN/pull/171, wrong paramaters when `G_padding_type` is not `reflect`.
Fix bug introduced by https://github.com/jolibrain/joliGAN/pull/172, define `get_feats` method for `segformer` feature extractor.
=> fix: segformer G and segformer feature extractor

data/online_creation.py
We used to store bbox ref coordinates before applying modifications (adding `mask_delta` and making the maske square). So, a part of the mask area could be outside of the final cropped image.
=> fix: wrong values for bbox ref coordinates

docker/Dockerfile.build, server/joligan_api.py
Add `git` to `Dockerfile.build` in order to print latest joliGAN server commit hash.
=> fix: joliGAN docker build with commit version log

models/modules/resnet_architecture/resnet_generator.py, models/networks.py, options/base_options.py
We use to have a bug which made feats going through resnet blocks two times in resnet_attn. We fixed but some models were trained that way, so we need an option to allow us to stille use those models.
New option :
`--G_backward_compatibility_two_times_resnet_blocks` : if true, feats will go through resnet blocks two times in resnet_attn
=> feat: option to go through resnet blocks two times (backward compatibility)

data/base_dataset.py, data/online_creation.py, data/temporal_dataset.py, data/unaligned_labeled_mask_dataset.py, data/unaligned_labeled_mask_online_dataset.py, options/base_options.py, train.py
Changes in dataloader to only reject an image when the path in not valid (for image or label). 
Any problem in data pre-processing (such as cropping dimension too small, label greater than the number of classes...) will be automatically resolved and a warning is printed in the logs.
There is a no warning mode.
=> chore: error warning data load

data/aligned_dataset.py, data/base_dataset.py, data/colorization_dataset.py, data/nuplet_unaligned_labeled_mask_dataset.py, data/single_dataset.py, data/temporal_dataset.py, data/unaligned_dataset.py, data/unaligned_labeled_dataset.py, data/unaligned_labeled_mask_dataset.py, data/unaligned_labeled_mask_online_dataset.py, models/base_model.py
Using BtoA was providing inverted labels to the semantics. This PR fixes it by definitely moving dataset direction out of models, into datasets.
=> fix: inverted BtoA direction labels, moving direction to datasets

docker/Dockerfile.devel, models/base_model.py, models/modules/discriminators.py, models/modules/vision_aided_d.py, models/networks.py, options/base_options.py, requirements.txt
This PR adds so-called vision-aided discriminators from https://github.com/nupurkmr9/vision-aided-gan.
In practice this allows adding up multiple large discriminators backbones that are lightly linearly fitted on top. This is akin our projected discriminators, though lighter. We expect them to speed up training even more.
New options:
- in `--D_netDs`: `vision_aided`
- `--D_vision_aided_backbones` to possibly add multiple. 
However, note that the linear probing and progressive ensembling that is at the core of the paper appears to be somehow custom to each GAN, and thus is not used here. The addition of more Ds appears useful though given the current and very initial training runs we have.
=> feat: multiple D via vision aided ensembling, https://arxiv.org/abs/2112.09130

models/networks.py, options/base_options.py
This PR :
- fixes broken usage of segformer for semantics
- allows using a partially trained model by skipping the pretrained `decode_head`
Note: it'd be better to have a generic `load_partial_state_dict` function in `models/modules/utils.py` cc @pnsuau
=> fix: segformer for semantics with optional partially pre-trained model

models/cut_semantic_mask_model.py, models/cycle_gan_semantic_mask_model.py, options/train_options.py
Option to compute semantic G loss on f_s outputs rather than on labels.
Usage:
```python train.py --train_sem_net_output```
=> feat: option to compute semantic G loss on f_s output

models/cut_semantic_mask_model.py
Domain B labels are now loaded when they are available, no matter what are the training options. (for cur_semantic_mask model)
=> fix: input_B_label loading when available

options/base_options.py
Change `f_s_class_weights` default to `[]` in order to avoid joligan server crash (during `BaseOptions` `parse_json` method).
=> fix : f_s_class_weights default to []

models/base_model.py, models/cut_model.py, models/cycle_gan_model.py, options/base_options.py
Support for amp mixed precision / cuda tensorcores with `--with_amp`.
I measure ~20% faster per image at training time.
Note: this is active on forward passes only.
=> feat: support for amp on forward ops

train.py
"latest" models weren't saved and exported when using `train_save_by_iter`. This PR fixes it.
=> Fix sv network

models/base_model.py, tests/test_run_semantic_mask_online.py
`backward` is made right after computing the loss between two successive frame in temporal criterion loss to limit the amount of memory used
=> feat: backward while computing MSE criterion loss

models/networks.py, options/base_options.py
This PR allows finer-grained control of the Generator depths.
New option:
- `--G_nblocks`, defaults to 9
=> chore: configurable number of blocks for resnet generators

models/base_gan_model.py, models/base_model.py, models/base_networks.py, models/cut_model.py, models/cycle_gan_model.py, models/gan_networks.py, models/re_cut_semantic_mask_model.py, models/re_cycle_gan_semantic_mask_model.py, models/segmentation_model.py, models/semantic_networks.py, models/template_model.py, models/test_model.py
This PR split `networks.py` into three specific files : `networks.py`, `gan_networks.py` and `semantic_networks.py`. 
For now, export doesn't work.
=> chore: split networks.py

models/base_model.py, models/gan_networks.py, models/modules/unet_generator_attn/unet_attn_utils.py, models/modules/unet_generator_attn/unet_generator_attn.py, options/base_options.py, tests/test_run_semantic_mask.py
Unet generator from https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models.
New options : 
- `G_unet_mha_inner_channel`: to specify inner channel size
- `G_unet_mha_num_head_channels` : to specify number of channels per attention head
Usage:
```
python3 train.py --G_netG unet_mha --G_nblocks 2 --G_unet_mha_inner_channel 64 --G_unet_mha_num_head_channels 32
```
=> feat: unet diffusion generator

models/cut_model.py, models/gan_networks.py, models/modules/cut_networks.py
This adds options `--alg_cut_netF mlp_sample_qsattn` and `sample_qsattn`, from https://arxiv.org/abs/2203.08483 and https://github.com/sapphire497/query-selected-attention
From the paper it doesn't seem gains are impressive but the whole mechanism makes sense.  In practice it seems this adds computations.
=> feat(ml): query-selected attention for contrastive patches, 2203.08483

models/base_gan_model.py, models/cut_model.py, models/cycle_gan_model.py, options/base_options.py
`alg_cut_lambda_GAN` is now replaced by `alg_gan_lambda` and can be used with both cut and cyclegan models
=> fix: lambda for GAN losses

models/gan_networks.py, options/base_options.py, tests/test_run_diffusion.py, tests/test_run_semantic_mask.py
Introduces new option `--G_unet_mha_channel_mults` with value `1 2 4 8` as default.
=> chore: reduce memory of unet_mha unit tests

data/online_creation.py, options/base_options.py
This PR changes the following options:
- `--data_online_creation_mask_delta_A` and `--data_online_creation_mask_delta_B`
Mask delta used to be the same for width and height, now we can use different values for both axis.
Usage:
```
python3 train.py --data_online_creation_mask_delta_A 10 --data_online_creation_mask_delta_B 10 15
```
=> feat(aug): configurable online mask delta augmentation by x and y axis

models/base_model.py
Note: this may require a fix in the future, to remove retain_graph requirement.
=> fix: multimodal GAN requires retain_graph for now

models/base_model.py, requirements.txt, train.py, util/visualizer.py
This PR displays networks architectures using torchinfo.
Displayed when `output_verbose` is enanled.
=> chore: display nets architecture on visdom

models/base_gan_model.py, models/cut_model.py, models/gan_networks.py, models/modules/utils.py, options/base_options.py, tests/test_run_nosemantic.py
This PR adds depth prediction and a dedicated discriminator (`--D_netDs depth`). 
Choices of depth network with `--model_depth_network`, among `["DPT_Large", "DPT_Hybrid", "MiDaS_small"]`.
Notes: 
- depth network is handled outside of the discriminator (whereas it could have been handled inside it, similarly to projected D). This allows working on having multiple discriminator architectures over depth predictions, to be updated.
~- tensor2img is hacked for the depth image to render properly, will fix.~ / fixed
=> feat: depth prediction and depth discriminator

models/base_model.py
This PR removes eval model when exporting models. It used to fail in multi gpu training.
=> fix: remove eval mode for export

models/palette_model.py, scripts/gen_single_image_diffusion.py, util/mask_generation.py
We use to take the ground truth image filled with random as conditioning image for palette model. We can now choose to take the ground truth image filled with a computed sketch. You can also use a computed mask with edges.
New options : 
- `--alg_palette_cond_image_creation` : choices `y_t`, `sketch`, `edges`
Usage:
```
python train.py --alg_palette_cond_image_creation chosen_option
```
=> feat: option to use a computed sketch as cond_image for palette

data/online_creation.py, data/self_supervised_temporal_dataset.py, data/temporal_dataset.py, models/palette_model.py, options/base_options.py
Option to use previous frame as y cond during palette training.
Usage:
```
python train.py --D_temporal_number_frames 2 --alg_palette_cond_image_creation previous_frame --data_dataset_mode self_supervised_temporal
```
=> feat: previous frame as y cond in palette

models/diffusion_networks.py, models/gan_networks.py, models/modules/unet_generator_attn/switchable_norm.py, models/modules/unet_generator_attn/unet_attn_utils.py, models/modules/unet_generator_attn/unet_generator_attn.py, models/palette_model.py, options/base_options.py, tests/test_run_diffusion.py
Replace groupnorm layers by batchnorm (and instance norm when 1D) in unet attn generator.
Note: for multigpu we need to convert batch norm into syncbatchnorm (automatically done in joligan) but for inference we need to convert it into batchnorm again (because inference is only done on first gpu).
New option : 
`--G_unet_mha_norm_layer` : choices : `["batchnorm","group32norm","switchablenorm"]`
=> feat: unet_attn change groupnorm into batchnorm

data/online_creation.py, data/temporal_dataset.py, data/unaligned_labeled_mask_online_dataset.py, options/base_options.py
New option to compute a random offset in bbox size at training time. It aims to robustify the model and to make it work with different bboxe sizes at inference time.
Usage:
```
python train.py --data_online_creation_mask_random_offset_A 0.1 --data_online_creation_mask_random_offset_B 0.1 0.0
```
=> feat: fixed bbox size for online creation

data/online_creation.py, scripts/gen_single_image_diffusion.py
This fixes masks over multiple boxes when only one is selected for inpainting at inference.
=> Fix gen single bbox mask

models/base_model.py, options/base_options.py, requirements.txt
New features:
- torch.compile with `--with_torch_compile`, works for palette diffusion models
Broken features:
- segformer ONNX export
- torch.compile fails on GANs, not on all models of generators and discriminators, but most often. Since torch.compile is still relatively experimental it is left available for GANs, but is crashing at the moment for those models.
=> chore: compatibility with pytorch2

docker/Dockerfile.build
Fixes the `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject` error at docker server startup.
=> chore: docker build image requirements requires upgrade for numpy

models/palette_model.py
`BatchNorm` are converted into `SyncBatchNorm` only when multigpu.
=> fix: batchnorm for single gpu

data/online_creation.py
This PR is a local fix, as joliGAN forces RGB elsewhere as well in data loading with diffusion. 
Full grayscale support would come with another PR.
=> fix: force RGB in online creation

data/online_creation.py
Online mask padding was missing when the image is for instance smaller than the requested crop size, and needs to be padded.
=> fix: online mask padding

models/modules/sketch_generation/hed.py, models/modules/sketch_generation/mbv2_mlsd_large.py, models/modules/sketch_generation/mlsd.py, models/palette_model.py, scripts/gen_single_image_diffusion.py, train.py, util/mask_generation.py, util/util.py
Added possibility for random edge detection method at training (Canny, HED, Hough, Depth)
Change `alg.palette_cond_image_creation` in your `train_config.json` model file to "random_sketch" for the model to choose a random edge detection function from #377 
```
python3 train.py --dataroot path/to/data/ --checkpoints_dir path/to/checkpoints/ --name noglasses2glasses \
--data_direction BtoA --output_display_env noglasses2glasses --gpu_ids 0,1 --model_type palette \ 
--train_batch_size 4 --train_iter_size 16 --model_input_nc 3 --model_output_nc 3 --data_relative_paths \ 
--train_G_ema --train_optim radam --data_dataset_mode self_supervised_labeled_mask \ 
--data_load_size 256 --data_crop_size 256 --G_netG unet_mha --data_online_creation_rand_mask_A \ 
--train_G_lr 0.00002 --train_n_epochs 200 …
```
=> feat: random edge detection method at training [2302.05543]

models/palette_model.py, util/mask_generation.py
For example to sample thresholds between 50 and 500, add:
```
python3 train.py [...] --alg_palette_sketch_canny_range 50 500
```
**or**
```
python3 train.py [...] --alg_palette_sketch_canny_range 500 50
```
The order of min and max range doesn't matter.
=> feat: choices for canny random thresholds

models/base_gan_model.py, models/base_model.py, models/cut_model.py, models/gan_networks.py, options/base_options.py
This PR adds mask automated generation from A to B. `f_s` is dually trained from a mask discriminator and from domain B masks when available. That is, the semantic pixel location is learned, as opposed to be specified as input.
- Added option: new `"mask"` discriminator
- Training run example
```
python3 train.py --dataroot /path/to/dataset --checkpoints_dir /path/to/checkpoints/ --name test_maskgen --output_display_freq 100 --output_print_freq 100 --gpu 0 --train_G_lr 0.0002 --train_D_lr 0.0001 --data_crop_size 256 --data_load_size 256 --data_dataset_mode unaligned_labeled_mask_online --model_type cut --train_semantic_mask --train_batch_size 1 --train_iter_size 5 --model_input_nc 3 --model_output_nc 3 --f_s_net unet --train_mask_out_mask --f_s_semantic_nclasses 3 --G_netG …
```
=> feat(ml): mask generation across domains for GAN semantics

data/__init__.py, data/base_dataset.py, data/self_supervised_labeled_mask_dataset.py, data/self_supervised_labeled_mask_online_dataset.py, data/self_supervised_temporal_dataset.py, data/temporal_dataset.py, data/unaligned_dataset.py, data/unaligned_labeled_cls_dataset.py, data/unaligned_labeled_mask_cls_dataset.py, data/unaligned_labeled_mask_cls_online_dataset.py, data/unaligned_labeled_mask_dataset.py, data/unaligned_labeled_mask_online_dataset.py, models/base_model.py, models/cut_model.py, models/cycle_gan_model.py, options/train_options.py, train.py, util/metrics.py
We can now compute FID, MSID and KID on a testset. Each `train_metrics_every`, we will compute fake images over all the testset and then compute metrics.
Note : The dataset needs to have `trainA` and `trainB` directories as usual **but also** `testA` and `testB` directories. 
Usage 
```
python3 train.py --train_compute_metrics_test --train_metrics_every 10000
```
=> feat: metrics for testset

Jenkinsfile
Ability to skip tests from PR, with label `ci:skip-tests`, useful for documentation PRs.
=> chore(ci): skip-tests

package.json, release.sh
To release:
```
yarn
./release.sh
```
Default behavior is to bump the major version.
=> Chore release script

options/train_options.py, train.py, util/visualizer.py
This PR:
- makes display optional with new choice `--output_display_type none` 
- makes joliGEN start a visdom server automatically only with `--output_display_visdom_autostart`
=> fix: visdom autostart and no display

models/base_model.py, options/train_options.py, train.py
This PR removes the metrics (FID, KID...) computation over trainset.
=> chore: remove metrics compute on trainset

scripts/generate_api_doc.sh
Github actions seem to fail because we try to connect JG server before launching it.
=> fix: server launching in generate api doc

.github/workflows/github-actions-doc-options-update.yml, docs/source/conf.py
- Options.rst tables are now converted from md to rst with pandoc (m2r is deprecated and had a bug), with a bash script to format them well for sphinx
- The "Edit on Github" button on the docs has been redirected to branch master instead of feat_jolidoc
1. Install act
2. Generate a github token from your github profile with repos access
3. run `export GITHUB_TOKEN="your_token"`
4. run `act -s GITHUB_TOKEN`
=> fix: rst autodoc + ci local testing

options/base_options.py
In documentation, https://www.joligen.com/doc/options.html `--D_netDs` does not show the different options, because they are dynamically created at runtime, put them into the option description instead.
=> chore: D_netDs values in documentation

examples/example_gan_glasses2noglasses.json, examples/example_gan_mario2sonic.json, models/base_diffusion_model.py, models/base_gan_model.py, models/modules/sam/sam_inference.py, models/modules/utils.py, models/palette_model.py, models/semantic_networks.py, options/base_options.py, requirements.txt, tests/test_run_semantic_mask_online.py
JoliGEN implementation to use [MobileSAM](https://github.com/ChaoningZhang/MobileSAM) for GANs and Diffusion models.
- GANs: `python3 train.py [...] --D_netDs sam --D_weight_mobile_sam models/configs/sam/pretrain/mobile_sam.pt --f_s_weight_mobile_sam models/configs/sam/pretrain/mobile_sam.pt --model_type_sam mobile_sam (default)`  
- Diffusion
- Mask refinement: `python3 train.py [...] --data_refined_mask --f_s_weight_mobile_sam models/configs/sam/pretrain/mobile_sam.pt --model_type_sam mobile_sam (default)`
- Edge detection: `python3 train.py [...] --alg_palette_cond_image_creation computed_sketch --alg_palette_computed_sketch_list sam -f_s_weight_mobile_sam models/configs/sam/pretrain/mobile_sam.pt --model_type_sam mobile_sam (default)`
\+ fixed some example config files because the …
=> feat: MobileSam implementation [2306.14289]

docs/source/training.rst, examples/example_ddpm_noglasses2glasses.json, examples/example_gan_mario2sonic.json, options/base_options.py
This PR fixes documentation, example model configurations, and allows automatic redistribution of `mask_delta` single value across all classes.
=> fix: training examples with mask_delta

models/base_gan_model.py, models/base_model.py, models/cut_model.py
This PR complements #411 with automatically refined mask target obtained with SAM.
Details: using mask semantics, masks may not have the same shape in A and B domains, e.g. when replacing a small object with a larger one. In practice, masks in A need to be modified (with `--data_online_creation_mask_delta_A`) to roughly accommodate the surface of the corresponding mask in B. This is so the semantic constraint can apply.
This PR allows `f_s` to automatically create a predictive mask for A that matches masks in B.
Example usage:
```
--D_netDs projected_d basic sam mask  --train_mask_no_train_f_s_A --train_mask_f_s_B --f_s_all_classes_as_one --data_refined_mask
```
=> feat(ml): GAN mask generator with sam refined target

models/cut_model.py
This PR enforces a larger NCE temperature with segformer generator architecture. I have this confirmed through multiple experiments with BDD100k.
Default NCE temperature of 0.07 from CUT appears to be too low, and this is corroborated by https://openaccess.thecvf.com/content/CVPR2021/papers/Wang_Understanding_the_Behaviour_of_Contrastive_Loss_CVPR_2021_paper.pdf in a more general setup.
=> fix: NCE with segformer architecture

models/modules/diffusion_generator.py
In `restoration_ddpm`, we are looping in reverse order.
We start at `t = num_timesteps_test - 1` and end at `t = 0`.
We use gammas in reverse order.
In `restoration_ddim`, we were looping in reverse order, but we are already reversing `tseq` in `tlist` and `prevt`.
We started at `tlist = 0` and ended at `tlist = num_timesteps_test - 1`.
We used gammas in order.
=> fix: reverse DDIM schedule

models/modules/diffusion_generator.py
`y_t` shape is `(batch_size, 3, size, size)`
`gamma_t` and `gamma_prevt` shape should be `(batch_size, 1, 1, 1)` instead of `(batch_size, 1)`
failed here: https://github.com/jolibrain/joliGEN/blob/bd16f1ede7f194dd1f411edc54b70f6838f1e7b5/models/modules/diffusion_generator.py#L401-L403
```
RuntimeError: The size of tensor a (42) must match the size of tensor b (128) at non-singleton dimension 2
=> fix: DDIM restoration when batch_size > 1

data/base_dataset.py, data/image_folder.py, data/online_creation.py, data/self_supervised_labeled_mask_online_ref_dataset.py, data/self_supervised_labeled_mask_ref_dataset.py, data/unaligned_labeled_mask_online_dataset.py, data/unaligned_labeled_mask_online_ref_dataset.py, data/unaligned_labeled_mask_ref_dataset.py, docs/source/dataloaders.rst, docs/source/datasets.rst, models/diffusion_networks.py, models/modules/diffusion_generator.py, models/modules/image_bind/helpers.py, models/modules/image_bind/imagebind_model.py, models/modules/image_bind/multimodal_preprocessors.py, models/modules/image_bind/transformer.py, models/modules/palette_denoise_fn.py, models/palette_model.py, options/base_options.py, scripts/run_tests.sh, tests/test_run_mask_online_ref.py, tests/test_run_mask_ref.py
This PR implements a dataloader for side / reference image in addition to the image input, used as additionnal conditioning.
- `--data_dataset_mode {unaligned_labeled_mask_ref,self_supervised_labeled_mask_ref}`
- `conditions.txt` format:
/path/to/img.png /path/to/ref.png
- `--data_dataset_mode {unaligned_labeled_mask_online_ref,self_supervised_labeled_mask_online_ref}`
- `conditions.txt` format:
/path/to/img.png /path/to/cond.txt
- `/path/to/cond.txt` format:
/path/to/ref1.png # ref image for first bbox
/path/to/ref2.png # ref image for second bbox
- `--alg_palette_conditioning ref` conditioning with embedding
- `--alg_palette_ref_embed_net clip` using CLIP
- `--alg_palette_ref_embed_net imagebind` using ImageBind
- `--alg_palette_cond_image_creation ref` conditioning with concat to input
=> feat: reference image conditioning [2306.08276]

scripts/gen_single_image_diffusion.py
Got the following error after running `gen_single_image_diffusion.py`:
```
File "joliGEN/scripts/gen_single_image_diffusion.py", line 286, in generate
img, mask, ref_bbox = crop_image(
ValueError: too many values to unpack (expected 3)
```
Just added a fourth variable to store the `box_ref_idx` returned from `crop_image` to make the code run.
Got the following error after running `gen_single_image_diffusion.py` with option `--cpu`:
```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```
Added what's advised in the error to fix the problem.
=> fixes: Missing bbox ref idx in from crop_image in gen_single_image_diffusion + allow inference on cpu

models/palette_model.py
Inference used to fail when `inference_num` < `batch_size`.
=> fix: inference_num for reference img

docs/source/quickstart_gan.rst
Fix links to example_gan_glasses2noglasses.json and https://arxiv.org/abs/2007.15651
=> fix: correct urls in quickstart_gan.rst

.pre-commit-config.yaml
This PR changes the version of python used for pre-commit (from 3.8 to 3.10).
=> fix: update python version for pre-commit

util/visualizer.py
We saved only the "metric" key, but reloaded it as the whole metrics_dict, which did not work.
=> fix: save whole metrics_dict so we can reload it

models/modules/projected_d/projector.py, options/base_options.py, tests/test_run_semantic_mask_online.py
This PR adds DinoV2 projected discriminator. 
- DinoV2: https://arxiv.org/abs/2304.07193 and https://github.com/facebookresearch/dinov2
- DinoV2 discriminator used in StyleGAN-T, see https://arxiv.org/abs/2301.09515 and https://github.com/autonomousvision/stylegan-t
- Feature layers to be extracted are taken and scaled from https://github.com/autonomousvision/stylegan-t/blob/main/networks/discriminator.py#L108C53-L108C53
=> feat(ml): DinoV2 feature-based projected discriminator

models/palette_model.py, options/__init__.py, options/base_options.py, options/common_options.py, options/helpers.py, options/inference_diffusion_options.py, scripts/run_tests.sh
```
>>> python train.py --help
usage: train.py --dataroot DATAROOT [--name NAME] [--suffix SUFFIX] [--gpu_ids GPU_IDS] [--with_amp] [--with_tf32] [--with_torch_compile] [--checkpoints_dir CHECKPOINTS_DIR] [--phase PHASE]
[--ddp_port DDP_PORT] [--warning_mode] [--test_batch_size TEST_BATCH_SIZE]
optional arguments:
--dataroot DATAROOT   path to images (should have subfolders trainA, trainB, valA, valB, etc) (default: None)
--name NAME           name of the experiment. It decides where to store samples and models (default: experiment_name)
--suffix SUFFIX       customized suffix: opt.name = opt.name + suffix: e.g., {model}_{netG}_size{load_size} (default: )
--gpu_ids GPU_IDS     gpu ids: e.g. 0 0,1,2, 0,2. use -1 for CPU (default: 0)
--with_amp            whether to activate torch amp on …
```
=> feat: specialized helpers for each model

README.md, docs/source/inference.rst, docs/source/training.rst, examples/example_cm_noglasses2glasses.json, examples/example_ddpm_SEN2VEN.json, examples/example_ddpm_mario.json, examples/example_ddpm_noglasses2glasses.json, examples/example_ddpm_unetref_viton.json, examples/example_ddpm_viton_tutorial.json, models/base_diffusion_model.py, models/cm_model.py, models/diffusion_networks.py, models/modules/cm_generator.py, models/modules/diffusion_utils.py, models/modules/unet_generator_attn/unet_generator_attn.py, models/palette_model.py, options/common_options.py, options/inference_diffusion_options.py, scripts/gen_single_image_diffusion.py, scripts/run_tests.sh, test.py, tests/test_run_cm.py, tests/test_run_diffusion.py, tests/test_run_pix2pix_diffusion.py, tests/test_run_sr_diffusion.py, train.py
This PR adds support for Consistency Models (https://arxiv.org/abs/2303.01469 and https://arxiv.org/abs/2310.14189).
Usage: 
```
python3 train.py --dataroot /data1/beniz/data/noglasses2glasses_ffhq --checkpoints_dir /home/beniz/checkpoints --name noglasses2glasses --config_json examples/example_cm_noglasses2glasses.json
```
Example: 
Note: some options (and thus doc & examples scripts have been modified) to accomodate the `BaseDiffusion` main class.
=> Consistency models with JoliGEN for inpainting

server/joligen_api.py, tests/test_api_predict_diffusion.py, tests/test_api_predict_gan.py
Passing `{"server": {"base64": true}}` option on inference api predict request will ask api server to return base64 image in request response.
=> feat: inference server option returns base64 image

scripts/canny_grid.py
This PR adds a way to quickly see the effects of a specific canny thresholds.
Example use:
```sh
python3 canny_grid.py --image-dir PATH/TO/DIR --output-dir OUTPUT/DIR --threshold1 0 --threshold2 1000
```
=> feat(scripts): canny thresholds grid plots

docs/source/docker.rst
`docker run` command was using `myjoligen` image name, image name has been replaced by `joligen_server`
=> Update docker.rst: fix image name

data/aligned_dataset.py, models/base_gan_model.py, models/cut_model.py
This PR adds supervised loss to GAN training when dataset is aligned.
New options:
- `--alg_cut_supervised_loss`: empty, L1 or MSE
- `--alg_cut_lambda_supervised`: supervised loss weight, default to 1.0
=> feat(ml): add supervised loss with GANs with aligned datasets

util/visualizer.py
Otherwise metrics cannot be compared across multiple runs with visdom.
=> chore: remove run name for test metrics on visdom, to allows for comparisons

models/base_model.py, options/train_options.py, train.py
This PR deactivates saving metrics images by default. On long runs, these images come in millions, and are useless in practice.
=> chore: do not save images used to compute metrics as default

models/cut_model.py, models/palette_model.py, options/train_options.py
Adds `--output_num_images` to limit the number of visualized images.
=> feat: max number of visualized images from train/test set

scripts/gen_single_image_diffusion.py
`img_orig` should stay in BGR mode.
Not sure what should be done for inpainting with `opt.data_image_bits > 8`, left as is.
=> fix: RGB order for diffusion inpainting

scripts/gen_single_image_diffusion.py
Apply Canny to the bbox  to avoid unwanted edges between original image and cond image.
- cond image
- Canny before fix
- Canny after fix
=> feat: better Canny for cond image with background

scripts/gen_single_image_diffusion.py
when using `--mask_delta`, the resulting bbox could have bounds outsize of the image
=> fix: clamp bbox to image size during inference

data/__init__.py, data/self_supervised_temporal_labeled_mask_online_dataset.py, docs/options.md, docs/source/inference.rst, docs/source/training.rst, models/base_model.py, models/diffusion_networks.py, models/modules/diffusion_generator.py, models/modules/unet_generator_attn/unet_attn_utils.py, models/modules/unet_generator_attn/unet_generator_attn_vid.py, models/palette_model.py, options/common_options.py, options/inference_diffusion_options.py, scripts/gen_vid_diffusion.py, scripts/run_tests.sh, tests/test_run_vid_diffusion_online.py
=> WIP: video_unet_generator_attn

models/cm_model.py
Pre-emptive PR for consistency models with input and output that bear different channel numbers.
=> fix: consistency models with input/output different channels

models/modules/diffusion_generator.py, models/modules/diffusion_utils.py, models/palette_model.py, util/mask_generation.py
Generate random Canny edges for a batch of images in the sequence.
=> random canny in batch

models/base_diffusion_model.py, models/modules/diffusion_generator.py, models/palette_model.py, util/mask_generation.py
random canny for each image in one sequence, and with canny dropout for each image. 
The dropout is hard coded for the moment, in  "models/palette_model.py" 
cond_image_nocanny, frame_select = fill_mask_with_canny_dropout(
self.gt_image,
self.mask,
self.opt.data_temporal_number_frames,
0.9,
)
I print frame_select is to check weather the selected frame in one sequence was suppose to have canny.
```
--dataroot /path/to/online_mario2sonic_full_mario  \
--checkpoints_dir  /path/to/checkpoints \
--name mario_vid_canny_random_dropout0.9_bs1it16_fix1  \
--gpu_ids 0,1,2    \
--output_print_freq 100   \
--output_display_freq 500  \
--data_dataset_mode  self_supervised_temporal_labeled_mask_online  \ …
```
=> random canny dropout for vid

scripts/gen_vid_diffusion.py
Video Inference Debugging
1 With Canny Edge Detection:
- First Frame: Apply Canny edge detection.
- Subsequent Frames: Use the same noise mask as the first frame.
2 Without Canny Edge Detection:
- All Frames: Use the same noise mask throughout the sequence.
cd scripts/
mkdir -p ../inference_mario_bz
python3 -W ignore::UserWarning  gen_vid_diffusion.py  \
--model_in_file  /path/to/checkpoints/test_mario_vid_example_canny_drop2/latest_net_G_A.pth  \
--img_in  /path/to/paths_part.txt  \
--paths_in_file   /path/to/online_mario2sonic_full_mario/trainA/paths.txt \
--mask_in /paths_part.txt    \
--dir_out ../inference_mario_bz  \
--sampling_steps 1000  \
--gpuid 2 \
~
=> feat(ml): inference_vid with canny

models/base_diffusion_model.py, models/palette_model.py
For video generation with Canny conditions, the option --alg_diffusion_vid_canny_dropout provides a range of dropout probabilities for the Canny dropout effect applied to each frame.
Example of execution.  It works with:
```
--dataroot /path/to/online_mario2sonic_full_mario  \
--checkpoints_dir  /path/to/checkpoints \
--name mario_vid  \
--gpu_ids 3    \
--output_print_freq 1   \
--output_display_freq 1   \
--data_dataset_mode  self_supervised_temporal_labeled_mask_online  \
--train_batch_size 2  \
--data_online_creation_crop_size_A 32  \
--data_online_creation_crop_size_B 32 …
```
=> vid_dropout_variance

models/diffusion_networks.py, models/modules/unet_generator_attn/unet_generator_attn_vid.py, options/common_options.py
Create an option for the maximum sequence length for video generation, --vid_max_sequence_length. The data_temporal_number_frames value should not exceed --vid_max_sequence_length
Example of execution. It works with:
```
--dataroot /path/to/online_mario2sonic_full_mario  \
--checkpoints_dir  /path/to/checkpoints \
--name  mario_vid   \
--gpu_ids 0    \
--output_print_freq 1   \
--output_display_freq 1   \
--data_dataset_mode  self_supervised_temporal_labeled_mask_online  \
--data_online_creation_crop_size_A 32  \
--data_online_creation_crop_size_B 32 \ …
```
=> option for max_sequence_length of video generation

models/palette_model.py
it works with:
python3 -W ignore::UserWarning train.py   \
--dataroot /data1/juliew/dataset/online_mario2sonic_full_mario/  \
--checkpoints_dir /data1/juliew/checkpoints     \
--name mario_vid        \
--gpu_ids 0     \
--model_type palette    \
--output_print_freq 1   \
--output_display_freq 1 \
--data_dataset_mode self_supervised_temporal_labeled_mask_online        \
--train_batch_size 2    \
--train_iter_size 1     \
--model_input_nc 3      \
--model_output_nc 3     \
--train_G_ema   \
--train_optim adamw     \
--G_netG unet_vid       \
--data_online_creation_crop_size_A 32   \
--data_online_creation_crop_size_B 32   \
--data_crop_size 32     \
--data_load_size 32     \
--data_online_creation_rand_mask_A      \
--train_G_lr 0.0001     \
--dataaug_no_rotate …
=> debug  vid metric when train bs > 1

models/palette_model.py
Dubug for canny range within the given threshold, it works with:
--dataroot /data1/juliew/ori_dataset/conti_3in1  \
--checkpoints_dir /data1/juliew/checkpoints  \
--name test_debug   \
--gpu_ids 0  \
--G_diff_n_timestep_train  2  \ …
=> vid canny dropout threshold 

data/self_supervised_vid_mask_online_dataset.py
This dataloader generates a pool of available starting frame numbers for each video series and selects one from that pool.  It works with:
--dataroot /path/to/data   \
--checkpoints_dir /path/to/checkpoints  \
--name test_debug   \
--gpu_ids 0  \
--G_diff_n_timestep_train  8  \ …
=> fix vid dataloader frame selection 

util/mask_generation.py
```
--dataroot  /path/to/data    \
--checkpoints_dir /path/to/checkpoints  \
--name test_conti  \
--gpu_ids 2  \
--data_relative_paths   \ 
--train_batch_size 2  \
--train_iter_size 8  \
--data_num_threads  16  \
--data_relative_paths \ 
--train_G_lr 0.0001 \
--G_diff_n_timestep_train  6  \
--data_temporal_frame_step 1 \ 
--alg_diffusion_cond_computed_sketch_list canny \
--alg_diffusion_cond_sketch_canny_range 50 100 \ …
```
=> fix for canny range  and dropout

data/self_supervised_vid_mask_online_dataset.py
--dataroot /path/to/dataset    \
--checkpoints_dir /path/to/checkpoints  \
--name test_debug   \
--gpu_ids 0  \
--G_diff_n_timestep_train  6  \
--alg_diffusion_cond_computed_sketch_list canny \
--diffusion_cond_sketch_canny_range 0 150 \ …
=> fix vid dataloader for frame limit

requirements.txt
https://github.com/huggingface/pytorch-image-models/commit/60f517c88327a64d44fb7259bb427c7658fdbb1b
=> chore: pin timm to v1.0.9 to avoid recently introduced issue

models/base_model.py, scripts/run_tests.sh, tests/test_run_vid_diffusion_online.py
```
--dataroot  /path/to/data    \
--checkpoints_dir  /path/to/checkpoints  \
--name test_debug   \
--gpu_ids 0  \
--train_batch_size 2  \
--test_batch_size 1  \
--G_diff_n_timestep_train  6  \
--alg_diffusion_cond_computed_sketch_list canny \ …
```
=> fix for vid metrics

options/inference_diffusion_options.py, scripts/gen_vid_diffusion.py
Add an option `--vid_fps` to specify the frames per second (FPS) for video generation, and an option `--vid_frame_extension_number` to include an additional frame for inference.
it works with 
```
cd scripts/
mkdir -p ../inference_mario/1017   && \
python3 -W ignore::UserWarning  gen_vid_diffusion.py  \
--img_in   /data1/paths_part.txt  \
--mask_in /paths_part.txt    \
--model_in_file  path/to/latest_net_G_A.pth  \
--paths_in_file   path/to/paths.txt\
--dir_out  ../inference_mario/1017  \
--sampling_steps 3  \
--gpuid 0  \
--vid_fps 1  \
--vid_frame_extension_number  6 \
```
=> add option for vid inference

requirements.txt
This is a temporary pin of the hf hub library, otherwise an update of diffusers is required, that fails the tests with img2img-turbo due to a bug in diffusers. The bug is going to be fixed (https://github.com/huggingface/diffusers/pull/9807), so this PR is a temporary fix to allow the CI to proceed in the meantime.
=> chore: diffusers update

data/self_supervised_vid_mask_online_dataset.py
--dataroot  /path/to/dataset     \
--checkpoints_dir    /path/to/checkpoints  \
--name test_debug  \
--gpu_ids 3 \
--train_batch_size 2  \
--test_batch_size 1  \
--G_diff_n_timestep_train  7  \
--alg_diffusion_cond_computed_sketch_list canny \ …
=> fix for dataaug(crop delta) during the video generation

models/base_model.py, options/train_options.py
Adds option `--train_finetune` to be used in combination with `--train_continue` in order to finetune networks by adding a new discriminator for instance, and removing losses.
Main usage: pre-train supervisedly and finetune on unpaired dataset with new discriminator.
=> feat: train_finetune 

scripts/gen_vid_diffusion.py
when do the inference type regeneration, the canny is the last frame of crop`
```
cd scripts/
python3  gen_vid_diffusion.py  \
--img_in  /data  \
--mask_in /data   \
--model_in_file  /path/to/model/latest_net_G_A.pth  \
--paths_in_file  /path/to/inference_paths.txt      \
--dir_out  /path/to/inference  \
--gpuid 0 \
```
when do the inference type cond_in, the canny is the edge of cond_in and can be adjusted:
```
cd scripts/
python3  gen_vid_diffusion.py  \
--img_in  /data  \
--mask_in /data   \
--model_in_file  /path/to/model/latest_net_G_A.pth  \
--paths_in_file  /path/to/inference_paths.txt      \
--dir_out  /path/to/inference  \
--cond_in  path/to/newimage.png  \
--alg_diffusion_sketch_canny_thresholds 40 100	\
--gpuid 0 \
```
=> fix vid inference of canny in situation of regeneration and  cond_in

models/base_model.py, options/train_options.py, util/fvd.py
add metric fvd for video generation, note that fvd requires  `data_temporal_number_frames>8` and  `test_batch_size >1`. It works with:
```
python3 -W ignore::UserWarning   train.py \
--dataroot   path/to/dataset    \
--checkpoints_dir   path/to/checkpoints/  \
--name  conti_fvd  \
--gpu_ids 1  \
--test_batch_size 2 \
--train_iter_size 2  \  
--data_num_threads  8  \
--G_diff_n_timestep_train   5  \
--data_temporal_frame_step 1 …
```
=> add metric fvd for video

options/base_options.py, util/parser.py
Before this PR unknown command line options were ignored which made it hard to spot typos.
Note:
`train_config.json` is already saved by default
`--save_config` makes sense only if `--config_json` was used
https://github.com/jolibrain/joliGEN/blob/master/util/parser.py#L19-L37
=> fix: warn user about unknown command line options

data/self_supervised_vid_labeled_mask_cls_online_dataset.py, models/modules/palette_denoise_fn.py, options/common_options.py
The ddpm_vid model already worked with Canny.  
With this PR, it now also works with alg_diffusion_cond_embed mask.
The command line is :
```
python3 -W ignore::UserWarning -W ignore::FutureWarning train.py \
--dataroot    path/to/path_vid  \
--checkpoints_dir  path/to/ckpt   \
--name  ddpm_vid_canny_mask  \
--gpu_ids 1  \
--data_dataset_mode  self_supervised_vid_labeled_mask_cls_online  \
--train_batch_size 3  \
--train_iter_size 8  \
--data_num_threads  16  \
--G_diff_n_timestep_train  10  \
--G_diff_n_timestep_test   4  \
--output_print_freq 10   \
--output_display_freq 1  \
--data_temporal_number_frames  8  \ …
```
=> feat(ml): extend ddpm_vid model to support alg_diffusion_cond_embed mask

models/modules/diffusion_generator.py, models/modules/diffusion_utils.py, models/palette_model.py, scripts/run_tests.sh, tests/test_run_ddpm_infer_ddim_online.py
works with command:
```
python3 -W ignore::UserWarning -W ignore::FutureWarning train.py \
--dataroot   path/to/data/vid  \
--checkpoints_dir   path/to/ckpt   \
--name  ddpm_ddim_debug  \
--gpu_ids 1  \
--train_batch_size 3  \
--train_iter_size 8  \
--data_num_threads  16  \
--dataaug_no_rotate \ 
--G_diff_n_timestep_test  1000  \
--G_diff_n_timestep_train  2000  \
--output_print_freq 10   \
--G_unet_vid_max_sequence_length  8  \
--output_display_freq 10000  \
--data_temporal_number_frames  8  \
--data_temporal_frame_step   1  \
--data_crop_size 64 \
--data_load_size 64  \ …
```
=> feat(ml): enable DDIM inference schedule in DDPM training

models/cm_model.py
Fixes a logic error in the CM model that broke "no-condition" training. The `else` block was incorrectly indented,which caused the inference function to skip the `netG.restoration` step. As a result, the model produced no output when running without condition inputs.
=> fix(ml): correct else indentation for no-condition training in CM model
