jolibrain/joliGEN

models/base_model.py
models/cycle_gan_semantic_mask_model.py
models/modules/resnet_architecture/mobile_resnet_generator.py
models/networks.py
scripts/export_jit_model.py
scripts/export_onnx_model.py
scripts/gen_dd_single_image.py
scripts/gen_jit_single_image.py
scripts/gen_single_image.py

This PR adds model JIT export, and requires internal changes, especially decoupling network backbones with and without decoder.

feat: scripts to export generator to JIT and to transform a single image

---

scripts/export_jit_model.py
scripts/gen_dd_single_image.py
scripts/gen_jit_single_image.py

Tracing instead of scripting + fixes and options.

fix: export & inference scripts for new encoder/decoder architectures

---

models/modules/resnet_architecture/mobile_resnet_generator.py

Refactoring needed before adding CUT model.

refactor: mobile resnet encoder can return intermediate features

---

models/cut_model.py
models/modules/cut_networks.py
models/networks.py
models/patchnce.py
options/base_options.py
options/train_options.py
train.py
util/util.py

This PR implements work in https://arxiv.org/abs/2007.15651 and uses code from https://github.com/taesungp/contrastive-unpaired-translation
command line : `python3 path/to/train.py --dataroot path/to/data --checkpoints_dir path/to/checkpointdir --lr 0.0002 --D_lr 0.0002 --crop_size 128 --load_size 128 --dataset_mode unaligned_labeled_mask --model cut --netG mobile_resnet_9blocks --batch_size 1 --input_nc 3 --output_nc 3`

feature: first cut model 

---

models/cut_semantic_mask_model.py

feat: contrastive classifier noise

---

data/image_folder.py
data/unaligned_labeled_mask_dataset.py
models/cut_semantic_mask_model.py
models/cycle_gan_semantic_mask_model.py

This allows domain B to not have labels, with CUT and CycleGAN + semantics.

fix: allow for domain B to have no semantic labels

---

models/base_model.py
models/modules/utils.py
train.py

Multi gpu can now be used with cut model.

fix: multigpu for cut model

---

data/__init__.py
data/unaligned_labeled_mask_dataset.py

Allos for image reading failure without killing the whole training run

Fix image reading failure

---

data/base_dataset.py
options/base_options.py

feat: generic image augmentation

---

train.py

Fix to a wrong indentation. Because of that each model used to be saved from each gpu.

fix: wrong indentation

---

models/base_model.py
options/train_options.py
util/diff_aug.py

Implementation of differential augmentation during GAN training (cf https://github.com/mit-han-lab/data-efficient-gans).

feat: diff augment

---

data/__init__.py
options/base_options.py
train.py

We use to create the dataset for each gpu, now we only create it once. We also create visualizer only once now.

fix: dataset created once, one dataloader per gpu

---

data/online_creation.py
data/unaligned_labeled_mask_dataset.py
options/train_options.py

New option to consider all classes as the same one (foreground vs background)/

feat : option to consider all classes as one

---

data/online_creation.py
data/unaligned_labeled_mask_online_dataset.py

Cleaning images and labels paths takes time. So, now, we can  save and load it.

Sv path clean

---

models/cut_semantic_mask_model.py
models/cycle_gan_semantic_mask_model.py

This option allow us to only train f_s model on domain B.

feat : add option not to train f_s on domain A

---

models/base_model.py
options/train_options.py
util/diff_aug.py

Now we use torchvision.transforms for differentiable augmentations.

feat: use torchvision.transforms for differentiable augmentations

---

data/online_creation.py

We are now able to load masks with multiple bounding boxes using online creation.

fix: online mask loading with multiple bboxes

---

models/cut_model.py

fix: D_global optimization

---

data/unaligned_dataset.py
models/base_model.py
models/cut_model.py
models/modules/loss.py
models/modules/projected_d/blocks.py
models/modules/projected_d/discriminator.py
models/modules/projected_d/projector.py
models/networks.py

Adds projected discriminator from https://arxiv.org/abs/2111.01007 and https://github.com/autonomousvision/projected_gan
For using the projected discriminator:
- `--netD projected_d`
- `--gan_mode projected`

feat: projected discriminator

---

models/base_model.py
models/cut_model.py
models/cut_semantic_model.py
models/cycle_gan_model.py
models/modules/loss.py
options/train_options.py
train.py
util/image_pool.py
util/visualizer.py

Implementation of https://arxiv.org/abs/2111.06849
Example of a command line : 
`python3 /home/pnsuau/joliGAN/train.py --dataroot /path/to/data--checkpoints_dir /path/to/checkpoint --name name --display_env display_env   --dataset_mode unaligned_labeled_mask --model cut_semantic_mask --netG mobile_resnet_attn --batch_size 1 --iter_size 4 --fs_light --train_f_s_B --use_label_B --out_mask --no_train_f_s_A --lambda_out_mask 100 --D_noise 0.01 --adaptive_pseudo_augmentation`
Options to modify : 
- `APA_target` : the APA target target (target used to adjust APA probability.
- `APA_p` : initial APA probability
- `APA_every` : it defines how often APA will be perfomed

feat: deceiving D for GAN training

---

data/base_dataset.py
data/unaligned_labeled_mask_online_dataset.py

We used to save `paths_sanitized.txt` in dataroot directory, now it's in checkpoints directory.

fix: saving paths_sanitized in checkpoints dir

---

train.py

Each process has now only access to a single gpu.

fix: only one gpu visible in each process

---

models/cut_model.py
models/cycle_gan_model.py
options/train_options.py

Option to display fake - real images, useful when processing object removal.

feat: option to display real image - fake image

---

README.md
options/base_options.py
scripts/run_tests.sh
server/joligan_api.py
tests/conftest.py
tests/test_run_horse2zebra.py
train.py

First joliGAN test : launching two trainings, cut and cyclegan on horse2zebra dataset through 1 epoch of 10 iterations.
Commandline:
```
bash /home/pnsuau/code/joliGAN/scripts/run_tests.sh /path/to/dir
```
Please note that you need a directory to download the dataset and store checkpoints from trainings.

feat: initial unit test set

---

models/cut_model.py
models/modules/attn_network.py
models/modules/mobile_modules.py
models/modules/resnet_architecture/resnet_generator.py
models/modules/segformer/segformer_generator.py
models/modules/segformer/utils.py
models/networks.py

Refactor resnet networks to remove duplicated code.

Refactor attn networks

---

models/cut_semantic_mask_model.py
models/cycle_gan_semantic_mask_model.py
options/train_options.py

Option to have two f_s networks, one for each domain.

feat: option to use a different f_s for domain B

---

data/base_dataset.py
data/unaligned_dataset.py
evaluate.py
models/base_model.py
options/evaluation_options.py
train.py

An evaluation script which allows us to compute FID after a chosen number of epochs. FID will be computed for different dataset sizes. FID values are saved a json file.
Example of a commandline : 
```
python3 joliGAN/evaluate.py -dataroot /path/to/data--checkpoints_dir /path/to/checkpoint --name name --display_env name  --dataset_mode unaligned --model cut --netG mobile_resnet_attn  --epoch_eval 10
```
Option to modify:
- `epoch_eval` , FID will be coputed after `epoch_eval` epochs.

feat : evaluation script

---

server/joligan_api.py
server/run.sh

Change API call to
```json
{
"server": {
"sync": false
},
"train_options": {
"dataroot": "...",
"..."
}
}
```

feat(server): add synchronous training

---

models/modules/projected_d/projector.py

We can now load torch script segformer weights or projected D.

feat: load segformer torchscript weights

---

data/base_dataset.py
models/cut_model.py
models/cut_semantic_mask_model.py
models/cut_semantic_model.py
models/cycle_gan_model.py
models/cycle_gan_semantic_mask_model.py
models/cycle_gan_semantic_model.py
models/modules/attn_network.py
models/modules/cut_networks.py
models/modules/resnet_architecture/resnet_generator.py
models/modules/segformer/segformer_generator.py
models/modules/stylegan_networks.py
models/modules/utils.py
models/networks.py
scripts/export_jit_model.py
scripts/export_onnx_model.py

Refactor opt use to make easier networks creation. Useless default values were removed too.

refactor: opt use for network creation

---

.github/workflows/github-actions-doc-options-update.yml
.github/workflows/requirements_github_actions.txt
models/modules/segformer/segformer_generator.py
models/modules/segformer/utils.py
scripts/generate_doc.py

Options doc will be updated automatically for each push on branch `master`.

feat: doc options auto update

---

scripts/run_tests.sh

Tentative removal of cache dirs from pytest.
https://github.com/pytest-dev/pytest/issues/3557

fix: tests with no cache

---

.pre-commit-config.yaml
README.md

Precommit hook to format the code before every commit.
Usage : 
- `pip install pre-commit`
- `pre-commit install`

feat: precommit black formatting

---

models/networks.py

Revert https://github.com/jolibrain/joliGAN/commit/767bc9834a061d08f5450e1e1f87992540ce73d0

chore : reset define D options

---

scripts/disc_single_image.py

This PR allows using D as a ranking tool.
Usage
```
python3 disc_single_image.py --model-in-file /path/to/laest_net_D.pth --model-type projected_d --img-size 180 --img-in /path/to/crop.png
```

feat: use the trained discriminator to rank generated images

---

models/modules/projected_d/projector.py
options/base_options.py

Implementation of right forward of feature extractors for vit models.

fix: get_feats feature extractor for projected D

---

models/modules/projected_d/projector.py
models/modules/utils.py
models/networks.py
requirements.txt

Pretrained segformer weight are now downloaded automatically when necessary for f_s and projected feature extractor networks.

feat: auto download segformer weights

---

options/base_options.py
server/joligan_api.py

json is now beautified & saved during a train call

fix: proper categories titles in schema + improve option saving

---

server/joligan_api.py

Use `launch_training` in joligan API.

fix: joligan api launch training

---

models/base_model.py
models/cut_model.py
models/cycle_gan_model.py
train.py

Generator weights are now exported during training (in torch jit and tensorrt).

feat: G weights export during training

---

models/base_model.py

We use to display loss values of the first gpu, now it's averaged accross all gpus.

fix: loss values averaged accross gpus

---

data/__init__.py
data/online_creation.py
data/temporal_dataset.py
models/base_model.py
models/cut_model.py
models/modules/projected_d/discriminator.py
models/modules/projected_d/projector.py
models/networks.py
options/base_options.py
train.py

Temporal discriminator.
New options:
- `D_temporal` : whether to use temporal discriminator
- `D_temporal_number_frames` : number of frames selected
- `D_temporal_frame_step` : number of frames between selected frames

feat: temporal discriminator

---

models/modules/resnet_architecture/resnet_generator.py

Re add deleted reflection pad in resnet models.

fix: resnet

---

models/base_model.py

fix: onnx opset version 11

---

data/temporal_dataset.py
models/base_model.py

Temporal D and context pixels weren't compatible.

fix: temporal D and context pixels compatibility

---

models/modules/projected_d/projector.py

See https://github.com/rwightman/pytorch-image-models/discussions/565#discussioncomment-611463

feat: allow ViT custom resolution at D projector init

---

models/modules/unet_architecture/unet_generator.py

Add `compute_feats` method to unet generators, which allows to use them with CUT.

feat: compute_feats for unet G

---

models/cut_semantic_mask_model.py
models/cycle_gan_semantic_mask_model.py
options/train_options.py

Option to apply semantic loss on identity images.
New option:
`--train_sem_idt` : if true apply semantic loss on identity
Usage:
```
python train.py --train_sem_idt

feat: semantic loss on identity

---

models/base_model.py
models/cut_model.py
models/cut_semantic_mask_model.py
models/modules/attn_network.py
models/modules/multimodal_encoder.py
models/modules/resnet_architecture/resnet_generator.py
models/modules/segformer/segformer_generator.py
models/networks.py
options/base_options.py
options/train_options.py
scripts/gen_single_image.py
train.py

This PR adds multimodal capabilities joliGAN, by using the cLR_GAN strategy described in https://arxiv.org/abs/1711.11586.
The idea is to complement the input image with random vector, that then allows for sampling a variety of B domain image from a single A domain input.
At training time, the random vector is concatenated to the input, while an encoder tries to recontruct it from the generated image. This ensures that G samples around the multiple possible realistic outputs, constrained by D.
Note: this implementation only applies to CUT at the moment, but without any restriction on semantics.

feat: multimodal generator with cLR-GAN strategy

---

options/base_options.py
scripts/run_tests.sh

Fix `get_schema` for doc update and add a test for doc auto generation.

feat: add test for doc generation

---

models/modules/attn_network.py
models/modules/segformer/segformer_generator.py
models/modules/segformer/utils.py

Auto resize of attention masks for attention generators (useful for segformers)

fix: auto resize of attention masks in segformer

---

models/base_model.py

Fix display of attention masks for attn genrators.

fix: attention masks display

---

models/modules/segformer/segformer_generator.py

Fix previous commit : https://github.com/jolibrain/joliGAN/commit/e3bf86acfb54cf4f52e10642d33ca3b2dafb53b0

fix: remove use_resize from segformer forward

---

models/modules/segformer/segformer_generator.py
models/networks.py
tests/test_run_semantic_mask.py

Add resize to segformer output when there is no final conv layer (ie when segformer is used as f_s net)

fix: segformer as f_s net

---

models/base_model.py
models/cut_semantic_mask_model.py
models/cycle_gan_semantic_mask_model.py
options/train_options.py
tests/test_run_semantic_mask.py
train.py
util/visualizer.py

option to compute MIoU for f_s predictions.
Usage
```
python train.py --train_mask_compute_miou  --train_mask_miou_every 1000```

feat: miou compute for f_s pred

---

data/online_creation.py
data/unaligned_labeled_mask_online_dataset.py

Fix to allow context pixels use with sanitize_paths

fix: context pixel for sanitize paths

---

data/online_creation.py
data/unaligned_labeled_mask_online_dataset.py
options/base_options.py
scripts/run_tests.sh
tests/test_run_semantic_mask_online.py

`data_online_creation_load_size`options to resize images and masks before processing (cropping...) when online data_loading.
New options:
- `data_online_creation_load_size_A` : for domain A
- `data_online_creation_load_size_A`: for domain B

feat : online load size

---

data/temporal_dataset.py
models/base_model.py
models/modules/projected_d/discriminator.py
tests/test_run_semantic_mask_online.py

…n resume (allows for finetuning)

fix: temporal discriminator image loading + skip temporal weights upon resume

---

options/base_options.py
train.py
util/util.py

We can now load a json file as training config.
Usage : 
```
python3 train.py --config_json path/to/json
```

feat : config file loading

---

models/base_model.py
models/cut_model.py
models/cycle_gan_model.py
options/train_options.py
train.py

Temporal loss between successive frames.
Usage :
`
python train.py --train_temporal_criterion --train_temporal_criterion_lambda 10
`

Temporal mse

---

models/base_model.py
options/train_options.py

jit model exporting is now an option.
Usage : 
```
python3 train.py --train_export_jit
```

feat : option for jit model exporting

---

models/base_model.py
models/cut_model.py
models/cycle_gan_model.py

Temporal criterion loss wasn't displayed, this PR fixes it.

fix: criterion temporal loss display

---

models/base_gan_model.py
models/base_model.py
models/cut_model.py
models/cycle_gan_model.py

`base_model` is now splitted into two different models : `base_model` and `base_gan_model`. The second inherits from the first one. It will be useful to integrate new models in the future.

chore: refactor to create base_gan_model

---

models/__init__.py

Fix for doc generation script.

fix: get schema should not compute base_gan_model

---

models/base_gan_model.py
models/base_model.py

Bug: semantic losses were printed flat with value 0 everywhere.

fix: semantic losses was initialized twice

---

models/base_model.py
models/modules/ittr/ittr_generator.py
models/networks.py
options/base_options.py
requirements.txt
tests/test_run_semantic_mask.py

From https://arxiv.org/abs/2203.16015 and sub-modules implementation from https://github.com/lucidrains/ITTR-pytorch
`--G_netG ittr`
ONNX export is broken for this model atm.

feat(ml): ITTR transformer arch for image2image - 2203.16015

---

README.md
models/cut_model.py
models/cycle_gan_model.py
models/monce.py
models/sinkhorn.py

Adding option `--alg_cut_nce_loss`
Based on https://github.com/fnzhan/MoNCE, paper https://arxiv.org/abs/2203.09333

feat(ml): adding MoNCE contrastive loss to CUT, 2203.09333

---

models/cut_model.py
tests/test_run_semantic_mask.py

Add option to activate MSE loss on idendity image in CUT models.
Usage : 
```
python3 train.py --alg_cut_MSE_idt --alg_cut_lambda_MSE_idt 1
```

feat: MSE identity loss for cut models

---

data/online_creation.py
data/unaligned_labeled_mask_dataset.py
data/unaligned_labeled_mask_online_dataset.py
options/base_options.py

This adds the option `--data_online_select_category` that allows training from a selection of bounding boxes from a dataset. This requires using `--data_sanitize_path`as well.

feat(aug): select bbox category through the path sanitization functionality

---

data/online_creation.py
data/self_supervised_labeled_mask_dataset.py
data/self_supervised_labeled_mask_online_dataset.py

This fixes two problems : 
- when bbox size > crop_size_max, crop_size_min wasn't updated to bbox_size
- self supervised dataloaders didn't return None when an error occured in data loading process

fix: online creation and selfsupervised

---

models/cycle_gan_model.py

This PR fixes visuals for cyclegan

fix: visuals for cyclegan

---

data/online_creation.py

When `crop_size > img_size` we now use zero padding.

fix: online creation when cropsize > imgsize

---

models/base_diffusion_model.py
models/diffusion_networks.py
models/gan_networks.py
models/modules/unet_generator_attn/diffusion_generator.py
models/modules/unet_generator_attn/unet_generator_attn.py
models/palette_model.py
options/base_options.py
scripts/gen_single_image.py
scripts/gen_single_image_diffusion.py
scripts/run_tests.sh
tests/test_run_diffusion.py

Add palette model. (from https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models)
Added options and parameters:
- `--model_type palette`
- `--G_unet_mha_n_timestep_train` the number of sampling timesteps at training time
- `--G_unet_mha_n_timestep_test` the number of sampling timesteps at test time

Palette 2111.05826

---

models/__init__.py
models/palette_model.py

This fixes the automatic doc generation.

fix: doc_gen for palette model

---

models/base_model.py
models/cut_model.py
models/cycle_gan_model.py

This PR fixes data dependency init method that sets vizualisation params.

fix: data dep init

---

models/base_gan_model.py
models/gan_networks.py
models/modules/loss.py
models/modules/projected_d/diffusion.py
models/modules/projected_d/discriminator.py
models/modules/projected_d/projector.py
options/train_options.py

Adds discriminator augmentation from https://github.com/Zhendong-Wang/Diffusion-GAN
The following options are added: `--dataaug_D_diffusion` and `--dataaug_D_diffusion_every`

feat(ml): diffusion-based augmentation for D, 2206.02262

---

scripts/gen_single_image_diffusion.py

This PR removes irrelevant code which comes from developpment and wasn't deleted.

fix: script for image gen using diffusion

---

models/base_gan_model.py

Fix `dataaug_D_diffusion` option call in discriminator loss

fix: dataaug_D_diffusion option

---

options/base_options.py
scripts/gen_single_image.py

fix: option to not set device when parsing json config file

---

models/base_model.py
models/modules/unet_generator_attn/unet_generator_attn.py
scripts/export_onnx_model.py

Onnc export for unet_mha is fixed.

feat: export for unet_mha

---

models/base_model.py
scripts/export_onnx_model.py
train.py
util/export/onnx.py

fix: onnx export

---

models/modules/utils.py

Trying to avoid https://github.com/isl-org/MiDaS/issues/193

chore: avoid midas 3.1 error

---

models/palette_model.py

Option to choose number of inference examples processed in palette models. They are useless for the training and they are pretty long to compute so we can now limit their number not matter what the batch size is. Default is 1.
Usage: 
```
python train.py --alg_palette_inference_num 1
```

feat: option for number of inferences (palette model)

---

models/palette_model.py

This PR fixes the display for palette model.

fix: display for palette model

---

models/base_gan_model.py
models/base_model.py

We can now compute class semantic loss on identity images.

fix: sem compute for cls on identity

---

options/train_options.py
util/visualizer.py

Number of columns for disdplay is computed automatically.

chore: ncols computed automatically for display

---

data/temporal_dataset.py
train.py
util/visualizer.py

When continuing a training, losses are reloaded and starting epoch is set automatically.

Chore reload losses

---

data/online_creation.py

fix online creation crop coordinates for temporal online creation

fix: online creation for temporal dataloader

---

data/online_creation.py
scripts/diffusion_options.py
scripts/gen_single_image_diffusion.py
scripts/gen_video_diffusion.py

Script to generate a video from diffusion models.
Usage:
```
python3 gen_video_diffusion.py --dataroot /path/to/data/paths.txt --video-out /temp.avi --model-in-file /path/to/checkpoints/latest_net_G_A.pth  --img-width 128 --img-height 128 --video-width 2064 --video-height 2000
```

feat: script to generate diffusion video

---

models/diffusion_networks.py
options/base_options.py

Add options to better control the UNet with multi-head attention model architecture.

chore: unet_mha additional options

---

models/base_model.py

fix: macs to flops

---

models/modules/diffusion_generator.py
models/palette_model.py

This PR fixes the mask clamping (needed when number of classes > 2). It also fixes the mask display.

fix: mask clamping and display for diff models

---

models/modules/loss.py
models/palette_model.py

This PR implements the multiscale loss from https://arxiv.org/pdf/2301.11093.pdf for diffusion process.
The loss is computed from img resolution to 32*32 by downsampling the noise and predicted noise. Image resolution needs to be a power of 2 (in theory).
Usage:
```
python3 train.py --alg_palette_loss multiscale    
```

[2301.11093] multiscale loss for diff 

---

models/diffusion_networks.py
models/modules/diffusion_generator.py
models/palette_model.py
scripts/diffusion_options.py
scripts/gen_single_image_diffusion.py

Add DDIM inference cf https://arxiv.org/pdf/2010.02502.pdf
With a non conditional model, it seems to work with at least 95 sampling, there is huge gap in generation quality between 90 sampling steps and 100. 
`--sampling_method` in [`ddpm`, `ddim`] with `ddpm` as default

feat: add ddim inference [2010.02502]

---

models/diffusion_networks.py
models/modules/unet_generator_attn/unet_generator_attn.py
options/base_options.py
requirements.txt
tests/test_run_diffusion.py
tests/test_run_diffusion_online.py

The UViT from https://arxiv.org/abs/2301.11093
I am getting good results from it, similar to the regular UNet with attention.

Feat uvit diffusion 

---

options/train_options.py
requirements.txt
train.py
util/visualizer.py

Adds support for https://github.com/aimhubio/aim
Works along with visdom.

chore: basic aim logging for losses and images

---

models/base_model.py
models/cut_model.py
models/cycle_gan_model.py
models/palette_model.py
train.py

Losses synchronization is only made when necessary (ie when printed), it results in a training loop time divided by 2.

feat: sync loss only when printing

---

options/train_options.py

parse_json fails with current default value

fix: output_display_type default value should be a list

---

models/base_model.py

Able to save a representation of the network as a (heavy) png image with arg `--output_display_networks`

fix: save networks img for diffusion

---

models/base_gan_model.py
models/cut_model.py
models/gan_networks.py
models/modules/sam/sam_inference.py
models/semantic_networks.py
options/base_options.py

Adds a signal that the segmentation map of real and fake domains should be very similar.

Discriminator based on SAM

---

.github/workflows/github-actions-doc-options-update.yml
.gitmodules
models/base_diffusion_model.py
models/base_gan_model.py
models/base_model.py
models/base_networks.py
models/palette_model.py
options/train_options.py
requirements.txt
train.py
util/metrics.py
util/visualizer.py

Usage : 
```
python3 train.py --train_compute_metrics
```

feat: add new metrics

---

models/diffusion_networks.py
models/modules/unet_generator_attn/unet_generator_attn.py
options/base_options.py
tests/test_run_diffusion.py

From https://arxiv.org/abs/2205.11487 annexe B.1

feat(ml): efficient UNet / 2205.11487

---

util/visualizer.py

This fixes the choice of visdom port when launching a new visdom server.

fix: visdom port for server launching

---

options/train_options.py
train.py
util/lion_pytorch.py

Lion optimizer from https://arxiv.org/abs/2302.06675

feat(ml): Lion optimizer [2302.06675]

---

models/modules/diffusion_generator.py
models/modules/resnet_architecture/resnet_generator_diff.py
models/modules/unet_generator_attn/unet_attn_utils.py
models/modules/unet_generator_attn/unet_generator_attn.py
models/palette_model.py

fix: clean code

---

data/single_dataset.py
models/palette_model.py
options/base_options.py
scripts/gen_single_image_diffusion.py
scripts/run_tests.sh
tests/test_run_sr_diffusion.py

Basic super-resolution with palette-like diffusion models.
API:
- `--alg_palette_task super_resolution`
- `--alg_palette_super_resolution_scale 2.0` 
- `--alg_palette_cond_image_creation low_res`  -> automated when task is `super_resolution` 
Notes: 
- current results at inference do not exactly match what is seen at training time, visually
- dataset is created in online manner, from bilinear down/up-sampling, using a paired dataset is coming up, possibly in another PR

feat(ml): diffusion super-resolution for palette

---

models/base_model.py

This PR adds PSNR metric (https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio) between ground truth image and generated images from the testset.
```
python3 train.py --train_compute_metrics_test
```

feat: add psnr metric

---

docs/options.md
models/base_diffusion_model.py
models/modules/sam/sam_inference.py
models/modules/utils.py
models/palette_model.py
options/base_options.py
scripts/gen_single_image_diffusion.py
util/mask_generation.py
util/util.py

Use `python3 train.py [...] --alg_palette_cond_image_creation computed_sketch --alg_palette_computed_sketch_list sam` to use Segment-Anything Model (SAM) for computing edge detection, with the following options:
|Parameter| Type | Default | Description |
|---|---|---|---|
|--alg_palette_sam_use_gaussian_filter|flag|False|whether to apply a gaussian blur to each SAM masks|
|--alg_palette_sam_no_sobel_filter|flag|True|whether to not use a Sobel filter on each SAM masks|
|--alg_palette_sam_no_output_binary_sam|flag|False|whether to not output binary sketch before Canny|
|--alg_palette_sam_redundancy_threshold|float|0.62|redundancy threshold above which redundant masks are not kept|
|--alg_palette_sam_sobel_threshold|float|0.7|Sobel threshold in % of gradient magintude| …

feat: sam for mask refinement and edges

---

models/base_model.py
train.py
util/visualizer.py

This PR allows to display test images used for metrics computation.

feat: display test images

---

data/temporal_dataset.py

Quick fix for a missing parameter : `mask_random_offset` for domain B

fix: random offset missing in crop_image

---

docs/source/choose.rst
docs/source/conf.py
docs/source/index.rst
docs/source/quickstart_ddpm.rst
docs/source/quickstart_gan.rst

* Rewrited the headers for consistency with all the files
* Corrected some typos
* Removed the table of content from homepage
* Removed hoverxref extension

[Doc] Fix :  rst headers format + typos + remove toc and hoverxref

---

data/__init__.py
data/temporal_labeled_mask_online_dataset.py
options/base_options.py

This PR renames the temporal dataloader.

chore:  rename temporal dataset

---

scripts/gen_single_image_diffusion.py

new options:
`--cond_keep_ratio`
`--cond_rotation`
`--cond_persp_horizontal`
`--cond_persp_vertical`
new saved files:
`..._orig_crop.png` : crop before insertion of cond image
`..._orig_bbox.json` : bbox of the original object
`..._generated_bbox.json` : bbox of the generated object, can differ because of aspect ratio

 feat: options for aspect ratio and augmentation of cond image

---

.github/workflows/github-actions-doc-options-update.yml
docs/source/index.rst
docs/source/quickstart_ddpm.rst
scripts/generate_doc.py

this PR that had been removed by mistake (+ rebase master)

Feat md2rst

---

models/base_model.py
options/train_options.py
util/metrics.py

This adds an option to choose which metric to compute.
New option:
```
--train_metrics_list : list of str choices : ["FID", "KID", "MSID", "PSNR"]
```
Usage:
```
python3 train.py --train_metrics_list KID MSID FID PSNR
```

feat: option to choose metrics to compute

---

models/palette_model.py

This PR fixes bugs in inference introduced by #431

fix: cond inference

---

README.md

I think adding this badge is a good way to let people know we have a documentation website available

Add doc badge on README

---

models/palette_model.py

This PR fixes palette inference when no mask conditioning.

fix: inference when no mask cond

---

models/base_model.py

This PR fixes a bug introduced by #431.

fix: network loading

---

scripts/gen_single_image_diffusion.py

fix: duplicate mask_delta values if only a single one is given, to apply it to both width and height (before: error when trying to change the heigt)

fix: mask_delta for inference diffusion

---

models/modules/diffusion_generator.py
models/modules/diffusion_utils.py
models/palette_model.py
scripts/diffusion_options.py
scripts/gen_single_image_diffusion.py

DDIM scheduler for the diffusion models. 
`--sampling_method` ddpm or ddim
Example usage:
```
python3 gen_single_image_diffusion.py --model-in-file /path/to/latest_net_G_A.pth --img-width 128 --img-height 128 --gpuid 3 --img-in /path/to/img.jpg --mask-in /path/to/mask.jpg --dir-out /path/to/test_ddim/ --sampling_method ddim --sampling-steps 100 --ddim_num_steps 40 --ddim_eta 1.0
```

feat(ml): DDIM scheduler

---

models/gan_networks.py
models/modules/projected_d/projector.py
options/base_options.py
tests/test_run_semantic_mask.py

This PR implements a new [projected discriminator](https://www.cvlibs.net/publications/Sauer2021NEURIPS.pdf) based on [Midas depth mode](https://pytorch.org/hub/intelisl_midas_v2/). 
Usage :
```
python train.py  --D_netDs projected_d --D_proj_network_type depth
```

feat: depth model as projector

---

data/online_creation.py
options/base_options.py
requirements.txt
tests/test_run_diffusion_online.py
tests/test_run_semantic_mask_online.py

Adds checks to mask_delta values to prevent unwanted behaviors. This does not catch everything, but at least a few corner cases.

fix: mask_delta checks

---

train.py

This PR implements command line saving in `command_line.txt` file.

feat: commandline saving

---

models/palette_model.py
models/semantic_networks.py

Fix inverted mask with sam refinement

---

scripts/gen_single_image_diffusion.py

- Not posible to perform diffusion inference using the SAM refined masks (code structure had changed)
- Not possible to perform diffusion inference with an 'inverted' mask (option not implemented)
- Both SAM refined and inverted masks are usable in `scripts/gen_single_image_diffusion.py`

fix: ddpm inference with sam masks + inverted masks

---

data/temporal_labeled_mask_online_dataset.py
data/unaligned_labeled_mask_online_dataset.py

`mask_delta` is broken due to wrong test on `mask_delta_{A,B}_ratio`.

fix: mask_delta ratio online check

---

data/base_dataset.py
data/self_supervised_temporal_dataset.py
data/temporal_labeled_mask_online_dataset.py
data/unaligned_labeled_mask_online_dataset.py
tests/test_run_diffusion_online.py

This PR fixes the temporal dataloader and:
- adds path sanitize option to self supervised loaders (for diffusion)
- adds training unit test with temporal supervised loader for diffusion

fix: temporal dataloader, with added path sanitize

---

models/modules/discriminators.py
models/modules/freq_utils.py
models/modules/resnet_architecture/resnet_generator.py
models/modules/unet_generator_attn/unet_generator_attn.py
models/modules/utils.py

This PR should fix the doc generation, by decoupling the loading of custom CUDA functions.

chore: wavelet utils and op built upon model py file loading

---

docs/source/metrics.rst
models/base_model.py
options/train_options.py
requirements.txt
scripts/run_tests.sh
test.py

This PR adds LPIPS metric from https://github.com/richzhang/PerceptualSimilarity
```
python3 train.py --train_metrics_list LPIPS ...
python3 test.py --test_metrics_list LPIPS ...

feat: add LPIPS metric

---

data/temporal_labeled_mask_online_dataset.py

This PR fixes the temporal data loader for diffusion models, that hangs indefinitely.

fix: diffusion with temporal data loader

---

models/base_model.py
models/gan_networks.py
models/modules/unet_generator_attn/unet_generator_attn.py
tests/test_run_semantic_mask.py

This PR adds `uvit` to `--G_netG` for GANs.

feat(ml): UViT for GAN

---

data/aligned_dataset.py
data/base_dataset.py
data/nuplet_unaligned_labeled_mask_dataset.py
data/online_creation.py
data/single_dataset.py
data/unaligned_dataset.py
data/unaligned_labeled_cls_dataset.py
data/unaligned_labeled_mask_cls_online_dataset.py
data/unaligned_labeled_mask_dataset.py
data/unaligned_labeled_mask_online_dataset.py
data/unaligned_labeled_mask_online_ref_dataset.py
data/unaligned_labeled_mask_ref_dataset.py
data/utils.py

This PR sets transparency color to black for all loaded images during the training.

fix: loading image with transparency

---

models/modules/diffusion_generator.py

This PR fixes the DDIM functions for accomodating reference tensors.

fix(ml): DDIM with reference image

---

scripts/gen_single_image_diffusion.py
scripts/gen_video_diffusion.py

This PR fixes the video generation from diffusion models (frame by frame).
It also improves multiple frames generation by avoiding reloading the model between frames.

fix: improved diffusion inference scripts, including video generation

---

data/online_creation.py
scripts/run_tests.sh

This PR implements a new of loading bboxes, from an image. 
Steps:

feat: extract bbox from img

---

models/modules/UNet_classification.py
models/modules/projected_d/blocks.py
scripts/run_tests.sh

This PR turns some BatchNorm layers into GroupNorm so that multi-gpu doesn't require many sync calls.

feat(ml): batchnorm to groupnorm in projected D and f_s unet to lower multi-gpu sync requirements

---

Jenkinsfile
data/base_dataset.py
data/temporal_labeled_mask_online_dataset.py
models/base_gan_model.py
models/base_model.py
models/cut_model.py
models/cycle_gan_model.py
models/modules/UNet_classification.py
scripts/run_tests.sh
tests/test_run_semantic_mask_online.py
train.py

This PR fixes the temporal discriminator (`--D_netDs temporal`) with semantics. 
Note: the tests were not catching this, unsure why atm.

fix: temporal discriminator with masks and bboxes

---

models/base_gan_model.py
tests/test_run_nosemantic.py

This fixes a bug with `--dataaug_APA` activated.

fix: APA augmentation on multiple discriminators

---

data/aligned_dataset.py
docs/source/dataloaders.rst
docs/source/training.rst
examples/example_ddpm_SEN2VEN.json
models/palette_model.py
scripts/gen_single_image_diffusion.py
scripts/run_tests.sh
tests/test_run_pix2pix_diffusion.py

Training:
``train.py --data_dataset_mode aligned --alg_palette_task pix2pix ...``
Inference:
``gen_single_image_diffusion.py --img-in source.png --alg_palette_cond_image_creation pix2pix --img_width 256 --img-height 256 ...``
`source.png` can be a lowres image for aligned super-resolution task, `img_width` and `img_height` used to specify target resolution

feat: pix2pix task for palette

---

scripts/gen_single_image_diffusion.py

This PR fixes inference with reference image. 
#568

fix(ml): inference for diffusion with reference image

---

models/base_gan_model.py
tests/test_run_semantic_mask_online.py

This PR fixes discriminator inference with mixed precision (amp).

fix: amp for discriminators

---

data/online_creation.py

More informative message for #571

chore: raise on missing semantic class

---

models/modules/projected_d/projector.py
options/base_options.py

Adds discriminators with registers (backbone from https://arxiv.org/abs/2309.16588)

feat(ml): dinov2 discriminator with registers

---

models/modules/projected_d/projector.py
options/base_options.py
tests/test_run_nosemantic.py

This PR adds support for projected discriminators based on SigLIP (https://arxiv.org/abs/2303.15343)

feat(ml): SigLIP based projected discriminators

---

models/modules/projected_d/projector.py
options/train_options.py

for `--D_proj_network_type siglip_vitb16`

chore: accomodating timm siglip vitb16 256

---

options/base_options.py
options/common_options.py
options/helpers.py
tests/test_run_diffusion_online.py
tests/test_run_semantic_mask_online.py

```
usage: gen_single_image_diffusion.py --model_in_file MODEL_IN_FILE --img_in IMG_IN --dir_out DIR_OUT [--name NAME] [--img_width IMG_WIDTH] [--img_height IMG_HEIGHT] [--cpu] [--gpuid GPUID]               
[--crop_width CROP_WIDTH] [--crop_height CROP_HEIGHT] [--bbox_width_factor BBOX_WIDTH_FACTOR] [--bbox_height_factor BBOX_HEIGHT_FACTOR]                               
[--sampling_steps SAMPLING_STEPS] [--seed SEED] [--mask_delta MASK_DELTA [MASK_DELTA ...]] [--mask_delta_ratio MASK_DELTA_RATIO [MASK_DELTA_RATIO ...]]               
[--mask_square] [--sampling_method {ddpm,ddim}] [--cls_value CLS_VALUE] [--previous_frame PREVIOUS_FRAME] [--mask_in MASK_IN] [--ref-in REF_IN] [--bbox_in BBOX_IN]   
[--nb_samples NB_SAMPLES] [--bbox_ref_id BBOX_REF_ID] [--cond_in COND_IN] …
```

fix: correct help for image generation scripts

---

data/base_dataset.py
data/online_creation.py
data/unaligned_labeled_mask_online_dataset.py
options/common_options.py

This PR adds `--data_online_random_bbox` for training generic inpainting models.

feat(data): random bbox for inpainting

---

data/aligned_dataset.py
data/base_dataset.py
models/base_diffusion_model.py
models/base_model.py
models/cm_model.py
models/cut_model.py
models/cycle_gan_model.py
models/modules/loss.py
models/palette_model.py
options/common_options.py
options/train_options.py
test.py
tests/test_run_pix2pix_diffusion.py
train.py
util/parser.py
util/util.py
util/visualizer.py

This PR adds 
- Aligned crops for pix2pix tasks such as super-resolution.
- Support for images with more than 8bit in mono-canal (gray) values

feat: images > 8bit and aligned crops for super-resolution

---

models/modules/loss.py
models/palette_model.py

This PR allows choosing between L1 and MSE for multiscale loss in diffusion model training.

Feat l1 mse multiscale loss

---

models/base_model.py
models/cm_model.py
models/modules/cm_generator.py
models/palette_model.py
train.py

Consistency models "karras" schedule depend on the current number of iterations, that needs to be recovered upon resume.

fix: consistency model schedule upon resume

---

data/single_dataset.py
scripts/run_tests.sh
train.py

Fixes bug in single dataset image loading, used for super-resolution with automatic source image downscale.

fix: single dataset

---

README.md
docs/source/index.rst
docs/source/training.rst
examples/example_ddpm_xview.json

Documentation on XView satellite imagery inpainting with DDPM.

doc: satellite imagery inpainting

---

models/base_model.py

This PR fixes the reference for GAN metrics computation.

fix: gan metrics reference

---

data/image_folder.py
docs/source/inference.rst
options/base_options.py
options/inference_diffusion_options.py
scripts/gen_single_image.py
scripts/gen_single_image_diffusion.py
tests/test_run_mask_online_ref.py
tests/test_run_mask_ref.py
util/visualizer.py

- rollback to cls
- fix inference scripts
- documentation

fix: crash in inference script, errors in documentation

---

models/cut_model.py
scripts/run_tests.sh
tests/test_run_pix2pix_gan.py

Should fix #635 and adds unit tests for aligned datasets with GANs and supervised loss.

fix: supervised loss for aligned GANs, with unit tests

---

data/__init__.py
data/aligned_dataset.py
data/base_dataset.py
data/colorization_dataset.py
data/nuplet_unaligned_labeled_mask_dataset.py
data/self_supervised_labeled_mask_cls_dataset.py
data/self_supervised_labeled_mask_cls_online_dataset.py
data/self_supervised_labeled_mask_dataset.py
data/self_supervised_labeled_mask_online_dataset.py
data/self_supervised_labeled_mask_online_ref_dataset.py
data/self_supervised_labeled_mask_ref_dataset.py
data/self_supervised_temporal_dataset.py
data/single_dataset.py
data/temporal_labeled_mask_online_dataset.py
data/unaligned_dataset.py
data/unaligned_labeled_cls_dataset.py
data/unaligned_labeled_mask_cls_dataset.py
data/unaligned_labeled_mask_cls_online_dataset.py
data/unaligned_labeled_mask_dataset.py
data/unaligned_labeled_mask_online_dataset.py
data/unaligned_labeled_mask_online_ref_dataset.py
data/unaligned_labeled_mask_ref_dataset.py
docs/source/datasets.rst
docs/source/training.rst
models/base_model.py
test.py
train.py
util/metrics.py
util/visualizer.py

This PR introduces support for multiple test sets while training.

feat(ml): multiple test sets

---

docs/source/UI.rst

Add extra information about running processes for `joligen_ui` in dev environment.

docs: extra info for joligen_ui dev

---

examples/example_ddpm_df2kost.json

Example of df2k, OST, Flat128 generic super-resolution example, similar to those in the litterature.

doc: example of generic super resolution

---

models/gan_networks.py
options/train_options.py

Fixes wrong selection of interpolation value input to the projected discriminators.

fix: interpolation size selection for projected discriminators

---

examples/example_cm_gan_noglasses2glasses.json
models/base_model.py
models/cm_gan_model.py
models/cm_model.py
models/diffusion_networks.py
options/common_options.py
scripts/gen_single_image_diffusion.py
tests/test_run_cm.py

This PR adds discriminator updates to consistency models.

feat(ml): CM with added discriminator

---

scripts/gen_single_image.py

Fixes inference with single channel > 8bit images.

fix: inference with images > 8bit and GANs

---

models/cut_model.py

This PR moves DISTS and LPIPS losses to piq.
Adds the following options : 
- `--alg_cut_lambda_perceptual`
- `--alg_cut_dists_mean`
- `--alg_cut_dists_std`

fix: supervised perceptual metrics all with piq and configurable lambda weight

---

models/diffusion_networks.py
models/modules/diffusion_generator.py

Preparing diffusion for input and output images with different channels.

fix: diffusion with input and output of different channel size

---

models/cm_model.py

Experimental, though working well: supervised perceptual losses with consistency models

feat: consistency models with supervised losses

---

models/cut_model.py

`--alg_cut_lambda_NCE 0.0` or negative removes the NCE loss.

fix: allowing for no NCE with cut

---

models/modules/utils.py
options/train_options.py

Adds `--train_lr_policy multistep` and `--train_lr_steps 50 100 ...`

feat: multistep lr scheduler

---

data/aligned_dataset.py
data/base_dataset.py
data/unaligned_dataset.py
data/utils.py

Replace original `load_image` with a more appropriate function.

fix: load_image replacement

---

models/cut_model.py
models/palette_model.py
test.py

fix: multiple test sets with test.py + SSIM

---

scripts/gen_vid_autoregressive_diffusion.py

In this test, half of the conditioned input is derived from the output of the last generation, which is the pixel inpainting result.  The identity changes during the different iteration of inference.
```
cd scripts/
for i in {1..10}; do
mkdir -p ../inference_conti/autoregressive_PR/run_$i && \
python3 -W ignore::UserWarning  gen_vid_autoregressive_diffusion.py   \
--img_in /data1/paths_part.txt \
--mask_in /paths_part.txt \
--model_in_file   path/to/checkpoints/latest_net_G_A.pth \
--paths_in_file  /path/to/only_bicycle16.txt  \
--dir_out ../inference_conti/autoregressive_PR/run_$i/ \
--sampling_steps 1000  \
--gpuid 0
done
```

vid autoregressive inference inpainting test

---

util/visualizer.py

Deactivated until reworked for newer versions of aim.

chore: deactivate aim images

---

models/cm_model.py

In Consistency Model, we set the visuals only during training.
This meant the images shown in the test table in Visdom were training images.
This fix restores the good visuals during testing.
The noisy images are not computed during testing, we hide them from the test table (instead of showing unrelated noisy images from the previous training batch).

fix: cm test visuals

---

models/palette_model.py
scripts/gen_vid_autoregressive_diffusion.py

With DDPM_vid in JoliGEN, videos can be generated up to `G_unet_vid_max_sequence_length` frames (default: 25).
This PR test an autoregressive method to generate longer videos while preserving consistency.
training works with :
```
python3 -W ignore::UserWarning -W ignore::FutureWarning train.py \
--dataroot   path/to/Unvalid_balance       \
--checkpoints_dir  path/to/checkpoint/  \
--name  imgv2  \
--gpu_ids 2  \
--train_batch_size 3  \
--data_num_threads  8  \
--train_save_epoch_freq 1       \
--train_G_lr 0.00001 \ …
```

Train DDPM_vid with Image + Canny Inputs and Enable Autoregressive Video Inference

---

models/palette_model.py

This PR introduces a new training option `--alg_palette_autoregressive`.  
With this flag enabled, the input alternates between:
- full batches using canny-edge inputs
- batches where one sample uses the full image and the rest are black
This enables experimenting with autoregressive training strategies for generating long videos using the autoregressive method.
- Added `-alg_palette_autoregressive` flag in argument parser
- Updated training loop to handle mixed canny/full-image batches
- Default behavior is unchanged when the flag is not set
- Intended for experimental training runs

fix: add autoregressive training option (--alg_palette_autoregressive)
